server:
  servlet:
    contextPath: /account
  port: 8888
  minThreads: 50
  maxThreads: 500
account:
  dsDriverClass: com.mysql.cj.jdbc.Driver
  dsMaxActive: 20
  dsUrl: jdbc:mysql://localhost:3306/akka_account?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
  dsUserName: akka_account
  dsPassword: akka_account
