server:
  servlet:
    contextPath: /amebapay
  port: 8000
  minThreads: 50
  maxThreads: 500
account:
  dsDriverClass: com.mysql.jdbc.Driver
  dsMaxActive: 20
  dsUrl: jdbc:mysql://localhost:3306/akka_account?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
  dsUserName: akka_account
  dsPassword: akka_account
